### PR TITLE
Add heapsort implementation

### LINKED ISSUE #22: Add heapsort implementation

### PR DESCRIPTION
**Pull request by jonasclauss**
Wrote the pseudo code from Mr. Weickert. Made a few tests and it seems like it's working. 
Bildschirmfoto 2021-07-23 um 13 58 07

### CODE REVIEW

**Comment by herrmanno** [comment]
@sachsenjonas I would suggest reordering the emitted events a little to simplify the printed output:

heapify

Beside the usage of 1-based indices (I added a short method documentation to point that out) the PR looks good to me.
Maybe tell me what you think about the altered event emission and if we find a solution there that pleases all of us this seems good to go (however, a bunch of short unit tests would be welcome, although not mandatory).

**Comment by sachsenjonas** [comment]
That looks much cleaner but wouldn't it be even better if we put it in the perfect order. Maybe it's just because of the picture but printing out the `Build-Up Heap` before printing the reordering of all elements would make more sense for me. But all in all it looks fine to me.

**Comment by jonasclauss** [comment]
@herrmanno looks perfect to me. thanks.

**Comment by herrmanno** [comment]
>That looks much cleaner but wouldn't it be even better if we put it in the perfect order.

I just added the message because the duplicate output of the final state after building up the heap seemed odd to me. The only thing the matters in this particular message are the (summed up) numbers of comparisons and writes.
Maybe when we change the message to something like 'Total: build up heap' it is clear that the following is the overall result (in regard to comparisons and writes) for the process of building up the max-heap.

**Comment by jonasclauss** [comment]
@herrmanno From my side everything is fine

**Comment by cbl** [comment]
In general I prefer this solution as it is closer to the pseudo code and thus easier to review.

**Review by cbl — APPROVED** [review]

**Comment by cbl** [comment]
@herrmanno Could you please add the default text color when no background is given, or did you already add this?

**Comment by herrmanno** [comment]
@cbl Removed any coloring for 'default' fields in the heapsort logging (based on [partial] cherry-picks of 12bb9337 and e3dfbfd2).
Bildschirmfoto 2021-07-23 um 18 51 58

**Comment by cbl** [comment]
@herrmanno perfect, thanks!

**Pull request merged**
